version: '2'

services:
# nginx provides the web server for rocketchat, chathost APIs and resourcespace
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - rocketchat
      - chathost
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000

# Builds the rocketchat server 
  rocketchat:
    image: rocketchat/rocket.chat:3.14.0
    container_name: rocketchat
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://chathost.derekmaxson.com
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - CREATE_TOKENS_FOR_USERS=true
      - MAIL_URL=smtp://smtp.email
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=derekmaxson@yahoo.com
      - ADMIN_PASS=!1TheWell
      - OVERWRITE_SETTING_API_Enable_Rate_Limiter=false
      - OVERWRITE_SETTING_FileUpload_ProtectFiles=false
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

# Database for rocketchat and chathost APIs
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
     - ../data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

# Chathost APIs
  chathost:
    image: 'node:10.15.0'
    container_name: chathost
    restart: always
    working_dir: /usr/src
    command: [ 'node', 'index.js' ]
    depends_on:
      - mongo
      - rocketchat
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - CHATHOST_PORT=2820
      - CHATHOST_LOGGING=console
      - CHATHOST_MONGO=mongodb://mongo:27017/chathost
      - CHATHOST_ROCKETCHAT=http://rocketchat:3000
      - CHATHOST_ROCKETCHATADMIN=admin
      - CHATHOST_ROCKETCHATPASSWORD=!1TheWell
    ports:
      - '2820:2820/tcp'
    volumes:
      - ./src:/usr/src
      - ./node_modules:/usr/src/node_modules

# Moodle nginx container (leverages PHP7.4 from https://github.com/wyveo/nginx-php-fpm)
# Overwrites nginx /etc/nginx/conf.d/default.conf with ./resources/moodle/conf.d/default.conf
  moodle:
    image: wyveo/nginx-php-fpm:php74
    container_name: moodle
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "1m"
    volumes:
      - ./resources/moodlenginx/conf.d:/etc/nginx/conf.d/
      - "../moodle:/var/www/moodle"
      - "../data/moodledata:/var/www/moodledata"
    ports:
      - 80:80
    depends_on:
      - mariadb

# Database for Moodle (mysql) and resourcespace
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
    ports:
      - '33306:3306'
    environment:
      - MARIADB_USER=moodleuser
      - MARIADB_PASSWORD=moodleuser
      - MARIADB_DATABASE=moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=!1TheWell
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - '../data/mariadb:/var/lib/mysql'

