---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker from AWS repo
  command: amazon-linux-extras install docker
  become: true
  notify: restart docker

- name: Give permissions to run docker as ec2-users
  command: usermod -aG docker ec2-user
  become: true

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Reboot device for changes to take effect
  reboot:
    post_reboot_delay=15
    pre_reboot_delay=2