---

- name: Install make to build node
  package: 
    name: gcc-c++, make
    state: latest
  when: ansible_user == 'ec2-user'
  
- name: Update repo for Node
  get_url: 
    url: https://rpm.nodesource.com/setup_14.x
    dest: /tmp/setup_14.x
    mode: "0775"
  when: ansible_user == 'ec2-user'
  
- name: Install setup script
  shell: /tmp/setup_14.x
  when: ansible_user == 'ec2-user'

- name: Install the latest version of Node
  package:
    name: nodejs
    state: latest
  
- name: Install the latest version of Git
  package:
    name: git
    state: latest

- name: Install Chathost repo
  git:
    repo: 'https://github.com/RT-coding-team/chathost.git'
    dest: "{{ document_root }}/chathost"  # With git declar the final directory
    clone: yes
    force: yes
    update: yes

- name: Set Permissions of ~/chathost
  ansible.builtin.file:
    path: "{{ document_root }}/chathost"
    recurse: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '776'

- name: Set data directory for Mongo
  ansible.builtin.file:
    path: "{{ document_root }}/data/db"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '777'

- name: Add the user 'nginx' 
  ansible.builtin.user:
    name: nginx
#    uid: 101
    group: '{{ ansible_user }}'

- name: Install node packages based on package.json.
  community.general.npm:
    path: "{{ document_root }}/chathost"

- name: Copy env to chathost directory
  template:
    src: env
    dest: "{{ document_root }}/chathost/.env"

- name: Copy run_docker_compose to chathost directory
  template:
    src: run_docker_compose.sh
    dest: "{{ document_root }}/chathost/run_docker_compose.sh"
    mode: '775'
    
- name: Launch Dockers (docker-compose up -d)
  command: 'sudo -u {{ ansible_user }} {{ document_root }}/chathost/run_docker_compose.sh &'

- name: Check chathost container before continuing
  wait_for:
    host: "localhost"
    port: 2820

- name: Set cron for system health to run every minute
  ansible.builtin.cron:
    name: "system.js"
    minute: "*"
    user: '{{ ansible_user }}'
    job: "/usr/bin/node {{ document_root }}/chathost/src/system.js >/tmp/systemjs.log 2&>1"
